name: Master - Run Tests and Build APK

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  test-unit:
    name: Run Unit Tests
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        run: bash ./gradlew testDebugUnitTest --stacktrace

  test-instrumentation:
    name: Run Instrumentation Test
    runs-on: macos-latest
    strategy:
      matrix:
#        api-level: [21, 23, 29]
        api-level: [30]
        target: [default, google_apis]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Pixel 4
          script: ./gradlew connectedDebugAndroidTest

  apk:
    name: Build APK
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk